### ISSUE TITLE
Suggestion: Replace Travis CI with GitHub Actions

### ISSUE THREAD

**Issue by joakimhellum** [hashicorp/terraform-provider-scaffolding#12]
Hi, many thanks for refactoring this repo for external audience. We have been using this as a template for a while. Both this repo and [terraform-provider-template](https://github.com/hashicorp/terraform-provider-template) is mentioned in the docs and they are very similar, but this seemed to be most up to date.

We noticed the Travis CI configuration was removed in some previous pull request. This is feature request / suggestion to add GitHub Actions workflow to replace Travis CI. 

Example GitHub Actions workflow (`.github/workflows/test.yml`):

```yaml
name: test

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  go-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2-beta
      with:
        go-version: '~1.13'
    - run: go test -v ./...

  golangci-lint:
    runs-on: ubuntu-latest
    container: golangci/golangci-lint:v1.24
    steps:
    - uses: actions/checkout@v2
    - run: golangci-lint run ./...

  tfproviderlint:
    runs-on: ubuntu-latest
    container: bflad/tfproviderlint:0.14
    steps:
    - uses: actions/checkout@v2
    - run: tfproviderlint ./...
```

Many thanks for considering,
