### ISSUE TITLE
Error: Could not find valid encryption key packet in key 62b905cxxxxxxx on action github import GPG

### ISSUE THREAD

**Issue by jbrunetext** [hashicorp/terraform-provider-scaffolding#46]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Terraform v0.13.5

### Affected Resource(s)
try toiport Key in github action 

### Terraform Configuration Files
```
name: release
on:
  push:
    tags:
      - 'v*'
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Unshallow
        run: git fetch --prune --unshallow
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14
      -
        name: Import GPG key
        id: import_gpg
        uses: paultyng/ghaction-import-gpg@v2.1.0
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          PASSPHRASE: ${{ secrets.PASSPHRASE }}
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

### Debug Output
Error: Could not find valid encryption key packet in key 62b905cxxxxxxx 

### Expected Behavior
import gpg private key

### Actual Behavior
🔮 Checking GPG private key
Error: Could not find valid encryption key packet in key 62b905cxxxxxxx 

### Steps to Reproduce
1)  gpg --armor --export-secret-key F1840E7D69CDF54D66XXXXXXXXXXXXXXXXX -w0 | xclip
2 create secrets on github 
3) git tag -f v0.0.1
