### ISSUE TITLE
Exclude unused goos/goarch flavours from goreleaser config

### ISSUE THREAD

**Issue by sergei-ivanov** [hashicorp/terraform-provider-scaffolding#91]
## Suggestion

Add explicit ignores to goreleaser config for the following flavours.

```yaml
  ignore:
    - goos: darwin
      goarch: '386'
    - goos: darwin
      goarch: 'arm'
    - goos: freebsd
      goarch: 'arm64'
    - goos: windows
      goarch: 'arm'
    - goos: windows
      goarch: 'arm64'

```

## Analysis

Currently, the suggested goreleaser configuration is as below, and go 1.17 builds almost the entire matrix. But the problem is that some of the flavours are not officially supported/endorsed by Terraform, and building them wastes resources and CI credits.

```yaml
  goos:
    - freebsd
    - windows
    - linux
    - darwin
  goarch:
    - amd64
    - '386'
    - arm
    - arm64
  ignore:
    - goos: darwin
      goarch: '386'
```

According to the [provider docs](https://www.terraform.io/registry/providers/os-arch) that link to this project, only the following flavours need to be built:

goos\goarch | amd64 | 386 | arm | arm64
-- | -- | -- | -- | --
darwin | x |   |   | x
freebsd | x | x |   |  
linux | x | x | x | x
windows | x | x |   |  

Looking at what various providers push to Terraform registry, it's the same matrix, but with one addition: `freebsd_arm`.
For example, [here](https://releases.hashicorp.com/terraform-provider-aws/3.74.0/) and [here](https://releases.hashicorp.com/terraform-provider-random/3.1.0/). Hence the suggested list of explicit ignores to align with the current state.
